# important
pretrained_model_name_or_path: THUDM/CogVideoX-5B-I2V
video_reshape_mode: random
height: 480
width: 720
max_num_frames: 49
data_root: datasets
dataset_file: seeds.txt
prompt_file: prompts.json
frame_intervals: [1]

num_train_epochs: 1
max_train_steps: 10000
checkpoints_total_limit: 2
checkpointing_steps: 150
train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 0.00005
pin_memory: true

scale_lr: false
lr_scheduler: cosine_with_restarts
lr_warmup_steps: 800
lr_num_cycles: 1
lr_power: 1.0

# unknown
revision: null
variant: null
cache_dir: null
video_column: video
caption_column: text
id_token: null
load_tensors: false
random_flip: null
dataloader_num_workers: 0
seed: null
rank: 64
lora_alpha: 64
mixed_precision: bf16
output_dir: tmp
fps: 8
skip_frames_start: 0
skip_frames_end: 0
resume_from_checkpoint: latest
gradient_checkpointing: true
enable_slicing: true
enable_tiling: true
noised_image_dropout: 0.05
ignore_learned_positional_embeddings: false
validation_prompt: null
validation_images: null
validation_prompt_separator: ':::'
num_validation_videos: 1
validation_epochs: null
validation_steps: null
guidance_scale: 6
use_dynamic_cfg: false
enable_model_cpu_offload: false
optimizer: adamw
use_8bit: false
use_4bit: false
use_torchao: false
beta1: 0.9
beta2: 0.95
beta3: null
prodigy_decouple: false
weight_decay: 0.0001
epsilon: 1.0e-08
max_grad_norm: 1.0
prodigy_use_bias_correction: false
prodigy_safeguard_warmup: false
use_cpu_offload_optimizer: false
offload_gradients: false
tracker_name: null
push_to_hub: false
hub_token: null
hub_model_id: null
logging_dir: logs
allow_tf32: true
nccl_timeout: 1800
report_to: tensorboard
